### ISSUE TITLE
enroll: allow pipe redirects for input(jwt) output(identity)

### ISSUE THREAD

**Issue by ekoby** [openziti/ziti-tunnel-sdk-c#168]
I believe this would be a more flexible approach than #160 

the following patterns should be supported:
```
$ echo $ENROLL_JWT | ziti-edge-tunnel enroll -j - -i identity.json

$ ziti-edge-tunnel enroll -j <(echo $ENROLL_JWT) -i identity.json 
```

**Comment by NicFragale** [comment]
@qrkourier FYI

Voting YES for this to be done.  Doing this aligns ZET with ZT in its ability to read from STDIN, but also (hopefully?) enables a FIFO PIPE to be used as well.

**Comment by qrkourier** [comment]
@ekoby I would love to have the option to pipe to stdin to enroll instead of reading from a JWT file. You're right, it would be more flexible. Looking at your second example with process substitution list as descriptor filename I don't believe any enhancements are necessary for that to work, and that's basically what @flouks and @NicFragale are looking for in both/all Linux tunnelers specifically for working within Docker container. The proposal is to allow a token value var to be preferred if present, and your second example is one way that could work. 

```bash
ziti-edge-tunnel enroll -j <(echo $ENROLL_JWT) -i identity.json
```

**Comment by NicFragale** [comment]
Hi Team - What is the status of this functionality?

**Comment by qrkourier** [comment]
@NicFragale Not forgotten!

**Comment by floucks** [comment]
Agreed on this approach vs #160. Let me know if I can assist here at all. Due to the way we're implementing, this feature would make our lives much much simpler!

**Comment by qrkourier** [comment]
I've implemented the stdin and env var methods of passing the token to `ziti-edge-tunnel` in a container in #185 .
